//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitcoin.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidDetail
    {
        public string BidDetailCode { get; set; }
        public string BidCode { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string PhotoConfirmation { get; set; }
        public string IFSCCode { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string BranchName { get; set; }
        public string BitCoinAddress { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Bid Bid { get; set; }
    }
}
