//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitcoin.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidPercentage
    {
        public string BPID { get; set; }
        public double Percentage { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
