
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Bitcoin.Data.DTO
{

using System;
    using System.Collections.Generic;
    
public partial class Commission
{

    public int CommissionId { get; set; }

    public int FromUserId { get; set; }

    public int ToUserId { get; set; }

    public double CommissionPrice { get; set; }

    public System.DateTime CommissionDate { get; set; }

    public int CommissionType { get; set; }

}

}
