//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitcoin.Data.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipCoin
    {
        public int PipCoinId { get; set; }
        public string OrderCode { get; set; }
        public double Amount { get; set; }
        public int Type { get; set; }
        public double InterestByDay { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
